### PR TITLE
Add SolarWinds identifier sw

### PR DESCRIPTION
**Pull request by cheempz**
Add the `sw` identifier for SolarWinds.

***
<a href="https://pr-preview.s3.amazonaws.com/solarwindscloud/tracestate-ids-registry/pull/14.html" title="Last updated on Nov 4, 2021, 11:02 PM UTC (dfe24e3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/tracestate-ids-registry/14/20999ac...solarwindscloud:dfe24e3.html" title="Last updated on Nov 4, 2021, 11:02 PM UTC (dfe24e3)">Diff</a>

### CODE REVIEW

**Comment by cheempz** [comment]
Apologies if you've already been notified, I'm unable to request reviews so tagging instead ;) @arminru @dyladan @SergeyKanzhelev

**Review by SergeyKanzhelev — APPROVED** [review]

**Comment by SergeyKanzhelev** [comment]
cc: @kalyanaj as well

**Review by kalyanaj — APPROVED** [review]

**Review by dyladan — APPROVED** [review]

**Review by SergeyKanzhelev — APPROVED** [review]

**Comment by SergeyKanzhelev** [comment]
@cheempz please rebase. Sorry for delay in review

**Comment by cheempz** [comment]
Thanks @SergeyKanzhelev, rebased.

**Pull request merged**
